'use client';

import Image from 'next/image';
import { useState } from 'react';
import { ArrowUpRight, Clock3, MapPin, Menu, Phone, X } from 'lucide-react';

const maps = 'https://www.google.com/maps/dir/?api=1&destination=La+Tradition%2C+27+Avenue+des+Diables+Bleus%2C+06300+Nice';
const images = {
  hero: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1800&q=85',
  pastry: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1100&q=85',
  bread: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=1100&q=85',
  croissant: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=85',
  counter: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=85'
};

function ImageCard({ src, alt, className='' }: { src:string; alt:string; className?:string }) {
  return <div className={`image-hover relative overflow-hidden ${className}`}><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div>;
}

export default function Home() {
  const [open, setOpen] = useState(false);
  const nav = [['Accueil','#accueil'],['Nos produits','#produits'],['Savoir-faire','#savoir-faire'],['Ã propos','#a-propos'],['Horaires','#horaires'],['Contact','#contact']];
  return <main>
    <header className="fixed top-0 z-50 w-full border-b border-white/20 bg-[#2c211c]/90 text-white backdrop-blur-md">
      <div className="mx-auto flex h-[76px] max-w-[1240px] items-center justify-between px-5 lg:px-8">
        <a href="#accueil" className="group flex items-center gap-3" aria-label="La Tradition, accueil"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-[#d9b08a] text-[#e5bd91]">â¦</span><span className="text-[13px] font-semibold tracking-[.24em]">LA TRADITION</span></a>
        <nav className="hidden items-center gap-7 lg:flex">{nav.map(([label,href])=><a key={href} href={href} className="text-[12px] uppercase tracking-[.14em] text-white/75 transition hover:text-white">{label}</a>)}</nav>
        <a href={maps} target="_blank" rel="noreferrer" className="hidden items-center gap-2 rounded-full bg-[#d9a878] px-5 py-3 text-[12px] font-bold uppercase tracking-[.12em] text-[#2c211c] transition hover:bg-white lg:flex">Nous trouver <ArrowUpRight size={15}/></a>
        <button className="lg:hidden" aria-label={open ? 'Fermer le menu' : 'Ouvrir le menu'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>
      </div>
      {open && <nav className="border-t border-white/15 bg-[#2c211c] px-5 pb-5 pt-3 lg:hidden">{nav.map(([label,href])=><a onClick={()=>setOpen(false)} key={href} href={href} className="block border-b border-white/10 py-4 text-sm uppercase tracking-[.14em] text-white/85">{label}</a>)}<a href={maps} target="_blank" rel="noreferrer" className="mt-4 flex justify-center rounded-full bg-[#d9a878] py-3 text-xs font-bold uppercase tracking-widest text-[#2c211c]">Nous trouver</a></nav>}
    </header>

    <section id="accueil" className="grain relative flex min-h-[720px] items-end overflow-hidden bg-[#382921] pt-24 text-white lg:min-h-[820px]">
      <Image src={images.hero} alt="Pain artisanal et viennoiseries dans une boulangerie" fill priority sizes="100vw" className="object-cover opacity-70" />
      <div className="absolute inset-0 bg-gradient-to-t from-[#2c211c] via-[#2c211c]/25 to-[#2c211c]/20" />
      <div className="relative mx-auto w-full max-w-[1240px] px-5 pb-20 lg:px-8 lg:pb-28"><p className="reveal mb-5 text-xs font-semibold uppercase tracking-[.27em] text-[#e5bd91]">Boulangerie Â· PÃ¢tisserie Â· Nice</p><h1 className="display reveal max-w-3xl text-5xl leading-[.98] [animation-delay:100ms] md:text-7xl lg:text-[96px]">Le goÃ»t de la<br/><i className="font-medium text-[#e5bd91]">tradition</i>, chaque jour.</h1><p className="reveal mt-7 max-w-md text-base leading-7 text-white/75 [animation-delay:200ms]">Une adresse de quartier Ã  Nice pour les essentiels de la boulangerie-pÃ¢tisserie, Ã  dÃ©couvrir dÃ¨s le petit matin.</p><div className="reveal mt-9 flex flex-wrap gap-3 [animation-delay:300ms]"><a href="#produits" className="flex items-center gap-2 rounded-full bg-[#f4e5d5] px-6 py-4 text-sm font-semibold text-[#2c211c] transition hover:bg-white">DÃ©couvrir nos produits <ArrowUpRight size={17}/></a><a href={maps} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-full border border-white/40 px-6 py-4 text-sm font-semibold transition hover:bg-white/10">Nous trouver <MapPin size={17}/></a></div></div>
      <div className="absolute bottom-8 right-8 hidden items-center gap-4 text-xs uppercase tracking-[.18em] text-white/60 lg:flex"><span className="h-px w-16 bg-white/40"/>27 Avenue des Diables Bleus</div>
    </section>

    <section className="bg-[#fffdf9] px-5 py-16 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[1fr_1.3fr] lg:items-end"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.22em] text-[#b8733d]">Lâessentiel, bien fait</p><h2 className="display max-w-md text-4xl leading-tight md:text-5xl">Une pause simple.<br/><i>Un vrai plaisir.</i></h2></div><p className="max-w-xl text-lg leading-8 text-[#5a4940]">La Tradition vous accueille Ã  Nice autour dâune offre de boulangerie-pÃ¢tisserie et de snacking. Une maison locale, ouverte chaque jour pour accompagner les matins pressÃ©s et les envies gourmandes.</p></div></section>

    <section id="produits" className="bg-[#f7f2ea] px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-[1240px]"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.22em] text-[#b8733d]">Ã dÃ©couvrir</p><h2 className="display text-4xl md:text-6xl">Nos produits</h2></div><p className="max-w-sm text-sm leading-6 text-[#6e5b50]">Les catÃ©gories qui font lâidentitÃ© dâune boulangerie de quartier. Le dÃ©tail de lâoffre est Ã  confirmer avec la maison.</p></div><div className="grid gap-5 md:grid-cols-2"><a href="#contact" className="group relative h-[420px] overflow-hidden rounded-sm bg-[#5c3e2c] md:h-[550px]"><ImageCard src={images.bread} alt="Pains dorÃ©s de boulangerie" className="absolute inset-0 h-full w-full opacity-90"/><div className="absolute inset-0 bg-gradient-to-t from-[#2c211c]/80 to-transparent"/><div className="absolute bottom-8 left-8 text-white"><p className="mb-2 text-xs uppercase tracking-[.2em] text-[#e5bd91]">01</p><h3 className="display text-4xl">Les pains</h3><span className="mt-4 inline-flex items-center gap-2 text-sm">Voir lâunivers <ArrowUpRight size={16}/></span></div></a><div className="grid gap-5 sm:grid-cols-2"><a href="#contact" className="group relative h-[300px] overflow-hidden rounded-sm bg-[#c8a17c] sm:h-full"><ImageCard src={images.croissant} alt="Viennoiserie dorÃ©e" className="absolute inset-0 h-full w-full"/><div className="absolute inset-0 bg-gradient-to-t from-[#2c211c]/75 to-transparent"/><div className="absolute bottom-6 left-6 text-white"><p className="mb-2 text-xs uppercase tracking-[.2em] text-[#f6d2ad]">02</p><h3 className="display text-3xl">Viennoiseries</h3></div></a><div className="grid gap-5"><a href="#contact" className="group relative h-[240px] overflow-hidden rounded-sm bg-[#bd8f66]"><ImageCard src={images.pastry} alt="PÃ¢tisserie artisanale" className="absolute inset-0 h-full w-full"/><div className="absolute inset-0 bg-gradient-to-t from-[#2c211c]/75 to-transparent"/><div className="absolute bottom-6 left-6 text-white"><p className="mb-2 text-xs uppercase tracking-[.2em] text-[#f6d2ad]">03</p><h3 className="display text-3xl">PÃ¢tisseries</h3></div></a><div className="flex min-h-[170px] items-end justify-between bg-[#eadccc] p-6"><div><p className="mb-2 text-xs uppercase tracking-[.2em] text-[#b8733d]">04</p><h3 className="display text-3xl">Pause dÃ©jeuner</h3></div><ArrowUpRight className="text-[#b8733d]"/></div></div></div></div></div></section>

    <section id="savoir-faire" className="bg-[#2c211c] px-5 py-20 text-white lg:px-8 lg:py-28"><div className="mx-auto grid max-w-[1240px] gap-14 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.22em] text-[#d9a878]">Le savoir-faire</p><h2 className="display max-w-lg text-4xl leading-tight md:text-6xl">Lâart de faire<br/><i className="text-[#e5bd91]">plaisir</i> au quotidien.</h2><p className="mt-7 max-w-md leading-7 text-white/65">Dans une boulangerie, tout commence par le geste juste et le plaisir du produit. La Tradition sâinscrit dans ce quotidien gourmand, au cÅur de Nice depuis 2017.</p><a href="#a-propos" className="mt-8 inline-flex items-center gap-2 border-b border-[#d9a878] pb-2 text-sm text-[#f1d0ae]">En savoir plus <ArrowUpRight size={16}/></a></div><div className="grid grid-cols-2 gap-4"><ImageCard src={images.pastry} alt="DÃ©tail d'une pÃ¢tisserie" className="h-64 rounded-sm lg:h-80"/><ImageCard src={images.counter} alt="Pain artisanal en gros plan" className="mt-16 h-64 rounded-sm lg:h-80"/></div></div></section>

    <section id="a-propos" className="bg-[#fffdf9] px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[1fr_1fr] lg:items-center"><div className="relative h-[420px] overflow-hidden bg-[#d7c0a8] lg:h-[580px]"><Image src={images.counter} alt="Ambiance chaleureuse de boulangerie" fill sizes="50vw" className="object-cover"/><div className="absolute bottom-5 left-5 bg-[#fffdf9] px-5 py-4"><p className="text-xs uppercase tracking-[.18em] text-[#b8733d]">Depuis</p><p className="display text-3xl">2017</p></div></div><div className="lg:pl-12"><p className="mb-5 text-xs font-bold uppercase tracking-[.22em] text-[#b8733d]">La maison</p><h2 className="display text-4xl leading-tight md:text-6xl">Une adresse<br/><i>Ã  Nice.</i></h2><p className="mt-7 max-w-md leading-8 text-[#5a4940]">La Tradition est une boulangerie-pÃ¢tisserie situÃ©e au 27 Avenue des Diables Bleus, dans le quartier de Nice. LâactivitÃ© de lâÃ©tablissement est dÃ©clarÃ©e depuis 2017.</p><p className="mt-5 max-w-md leading-8 text-[#5a4940]">Pour dÃ©couvrir lâoffre du jour, le plus simple reste de passer nous voir.</p></div></div></section>

    <section id="horaires" className="bg-[#eadccc] px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-2"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.22em] text-[#b8733d]">Ã deux pas de chez vous</p><h2 className="display text-4xl leading-tight md:text-6xl">Passez nous<br/><i>voir.</i></h2><div className="mt-10 flex items-start gap-4"><MapPin className="mt-1 text-[#b8733d]"/><div><p className="font-semibold">La Tradition</p><p className="mt-1 leading-7 text-[#6e5b50]">27 Avenue des Diables Bleus<br/>06300 Nice, France</p><a href={maps} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#2c211c] px-5 py-3 text-xs font-bold uppercase tracking-widest text-white transition hover:bg-[#563c2e]">Obtenir lâitinÃ©raire <ArrowUpRight size={15}/></a></div></div></div><div className="bg-[#fffdf9] p-7 md:p-10" aria-label="Horaires d'ouverture"><div className="flex items-center gap-3 border-b border-[#2c211c]/10 pb-5"><Clock3 className="text-[#b8733d]"/><h3 className="display text-3xl">Horaires</h3></div><div className="mt-5 space-y-3 text-sm">{['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'].map(day=><div key={day} className="flex justify-between border-b border-[#2c211c]/8 py-2"><span>{day}</span><span className="font-semibold">05:00 â 20:00</span></div>)}</div><p className="mt-5 text-xs leading-5 text-[#806e62]">Horaires publics Ã  confirmer par lâÃ©tablissement avant mise en ligne dÃ©finitive.</p></div></div></section>

    <section id="contact" className="bg-[#fffdf9] px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-[1000px] text-center"><p className="mb-5 text-xs font-bold uppercase tracking-[.22em] text-[#b8733d]">Une envie gourmande ?</p><h2 className="display text-4xl leading-tight md:text-7xl">On se retrouve<br/><i>Ã  la boulangerie.</i></h2><p className="mx-auto mt-7 max-w-lg leading-7 text-[#6e5b50]">Pour toute question ou information, Ã©crivez-nous Ã  lâadresse publique indiquÃ©e dans les annuaires. Pour les commandes, les disponibilitÃ©s sont Ã  confirmer directement avec la maison.</p><a href="mailto:saslatradition@gmail.com" className="mt-8 inline-flex items-center gap-2 border-b border-[#b8733d] pb-2 text-sm font-semibold text-[#7a4829]">saslatradition@gmail.com <ArrowUpRight size={16}/></a></div></section>

    <footer className="bg-[#2c211c] px-5 py-12 text-white lg:px-8"><div className="mx-auto grid max-w-[1240px] gap-10 md:grid-cols-[1.3fr_1fr_1fr] md:items-end"><div><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-[#d9b08a] text-[#e5bd91]">â¦</span><span className="text-[13px] font-semibold tracking-[.24em]">LA TRADITION</span></div><p className="mt-5 max-w-xs text-sm leading-6 text-white/55">Boulangerie-pÃ¢tisserie Ã  Nice.<br/>27 Avenue des Diables Bleus, 06300 Nice.</p></div><div><p className="mb-4 text-xs uppercase tracking-[.18em] text-[#d9a878]">Navigation</p><div className="grid grid-cols-2 gap-3 text-sm text-white/70">{nav.slice(0,4).map(([label,href])=><a key={href} href={href} className="hover:text-white">{label}</a>)}</div></div><div><p className="mb-4 text-xs uppercase tracking-[.18em] text-[#d9a878]">Horaires</p><p className="text-sm text-white/70">Tous les jours<br/><span className="text-white">05:00 â 20:00</span></p><a href={maps} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm text-[#e5bd91]">ItinÃ©raire <ArrowUpRight size={15}/></a></div></div><div className="mx-auto mt-12 flex max-w-[1240px] flex-col justify-between gap-3 border-t border-white/10 pt-5 text-xs text-white/35 md:flex-row"><span>Â© {new Date().getFullYear()} La Tradition</span><span>Site de prÃ©sentation â informations Ã  confirmer par lâÃ©tablissement</span></div></footer>

    <div className="fixed bottom-0 left-0 right-0 z-40 grid grid-cols-3 border-t border-[#2c211c]/10 bg-[#fffdf9]/95 text-center shadow-[0_-8px_24px_rgba(44,33,28,.08)] backdrop-blur-md md:hidden"><a href={maps} target="_blank" rel="noreferrer" className="flex flex-col items-center gap-1 py-3 text-[10px] font-bold uppercase tracking-wider text-[#7a4829]"><MapPin size={18}/><span>ItinÃ©raire</span></a><a href="#horaires" className="flex flex-col items-center gap-1 border-x border-[#2c211c]/10 py-3 text-[10px] font-bold uppercase tracking-wider text-[#7a4829]"><Clock3 size={18}/><span>Horaires</span></a><a href="mailto:saslatradition@gmail.com" className="flex flex-col items-center gap-1 py-3 text-[10px] font-bold uppercase tracking-wider text-[#7a4829]"><Phone size={18}/><span>Contact</span></a></div>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Bakery","name":"La Tradition","address":{"@type":"PostalAddress","streetAddress":"27 Avenue des Diables Bleus","postalCode":"06300","addressLocality":"Nice","addressCountry":"FR"},"email":"saslatradition@gmail.com","foundingDate":"2017","openingHours":"Mo-Su 05:00-20:00","url":"/"})}} />
  </main>;
}
